# Generated by Django 3.2.11 on 2024-10-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proid', models.CharField(max_length=5)),
                ('add', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('paymenttype', models.CharField(max_length=50)),
                ('total', models.PositiveIntegerField()),
                ('transactionid', models.CharField(max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registeration')),
            ],
        ),
    ]
