# Generated by Django 4.2.6 on 2024-12-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='register_new',
        ),
    ]
