# Generated by Django 4.2.6 on 2024-12-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_register_register_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_new',
            name='add',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register_new',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='register_new',
            name='mob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register_new',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register_new',
            name='password',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
