# Generated by Django 4.2.6 on 2024-12-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_blog1_alter_blog_email_alter_blog_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
